### ISSUE TITLE
6.8.2: Docker image serves blank page: "WebAssembly unreferenced variable"

### ISSUE THREAD

**Issue by anoduck** [bakape/shamichan#1305]
I understand there are breaking changes occurring in the master branch of the repo, so I attempted to use the most recent release, assuming that it contained a working version of meguca. I am hesitant to downgrade to a lower release than 6.8.2 due to it being over two years old.

The error occurs in both the latest docker image for meguca from docker repository and image built from the latest release of meguca hosted here. Meguca serves a blank page and browser console output is the following error:

```js
Uncaught (in promise) JsValue(TypeError: a(...) is undefined
Wt/<@http://localhost/assets/client/1.js:1:26497
F@http://localhost/assets/client/1.js:1:19967
Wt@http://localhost/assets/client/1.js:1:26467
__wbg_generateKey_336ce2b984e7bccf@http://localhost/assets/client/index.js:1:8557
@http://localhost/assets/client/c4082a231d5fd9cd59c5.module.wasm:wasm-function[175]:0x16cb0
@http://localhost/assets/client/c4082a231d5fd9cd59c5.module.wasm:wasm-function[185]:0x3990e
@http://localhost/assets/client/c4082a231d5fd9cd59c5.module.wasm:wasm-function[549]:0xde947
@http://localhost/assets/client/c4082a231d5fd9cd59c5.module.wasm:wasm-function[1124]:0xfb61e
k@http://localhost/assets/client/1.js:1:19735
o@http://localhost/assets/client/1.js:1:19476
promise callback*wr@http://localhost/assets/client/1.js:1:28881
__wbg_then_c2361a9d5c9a4fcb@http://localhost/assets/client/index.js:1:10638
@http://localhost/assets/client/c4082a231d5fd9cd59c5.module.wasm:wasm-function[474]:0xd418a
@http://localhost/assets/client/c4082a231d5fd9cd59c5.module.wasm:wasm-function[758]:0xf026b
@http://localhost/assets/client/c4082a231d5fd9cd59c5.module.wasm:wasm-function[892]:0xf69ef
@http://localhost/assets/client/1.js:1:11668
c@http://localhost/assets/client/index.js:1:13306
promise callback*@http://localhost/assets/client/index.js:1:15667
c@http://localhost/assets/client/index.js:1:13306
@http://localhost/assets/client/index.js:1:15634
@http://localhost/assets/client/index.js:1:15642
)
```

Running Meguca with logging set to `DEBUG` did not generate any additional output.

**Comment by bakape** [comment]
The docker images hosted on DockerHub are not of v6. There are no images hosted for v6 at all and you are expected to use `docker-compose` to build the image in situ, if not choosing to host natively. The error you posted is definetly from the master branch. What problems do you have with running any of the releases? They work for me, so there might be a difference in environment or lack of documentation somewhere.

**Comment by anoduck** [comment]
The archive for release 6.8.2 is the version currently incorporated into my docker-compose configuration, and I could have sworn my local image was built from it. Regardless, I am building it again.

**Comment by anoduck** [comment]
😳Well... Apparently... I didn't...

Excuse me, while I tuck tail, and run away now... run away... run away...
